"""Generate agents.txt file content from analysis results."""

from __future__ import annotations

from urllib.parse import urlparse

from app.models.schemas import PageAnalysis
from app.utils.helpers import get_domain


def _detect_api_endpoints(pages: list[PageAnalysis]) -> list[str]:
    """Heuristic detection of API-like paths from links."""
    api_patterns = ["/api/", "/v1/", "/v2/", "/graphql", "/rest/", "/webhook"]
    endpoints = set()
    for page in pages:
        for link in page.links:
            for pattern in api_patterns:
                if pattern in link.lower():
                    endpoints.add(link)
    return sorted(endpoints)[:10]


def _detect_forms_and_actions(pages: list[PageAnalysis]) -> list[str]:
    """Detect common interactive capabilities from page structure."""
    capabilities = set()
    for page in pages:
        meta = page.meta_tags
        headings_text = " ".join(h["text"].lower() for h in page.headings)

        if any(kw in headings_text for kw in ["contact", "liên hệ", "get in touch"]):
            capabilities.add("contact-form")
        if any(kw in headings_text for kw in ["search", "tìm kiếm"]):
            capabilities.add("search")
        if any(kw in headings_text for kw in ["login", "sign in", "đăng nhập"]):
            capabilities.add("authentication")
        if any(kw in headings_text for kw in ["cart", "checkout", "giỏ hàng"]):
            capabilities.add("e-commerce")
        if any(kw in headings_text for kw in ["book", "schedule", "đặt lịch"]):
            capabilities.add("booking")
        if any(kw in headings_text for kw in ["subscribe", "newsletter"]):
            capabilities.add("newsletter-subscription")

    return sorted(capabilities)


def generate_agents_txt(pages: list[PageAnalysis], base_url: str, special_files: dict[str, bool] | None = None) -> str:
    """Generate agents.txt — a file declaring what AI agents can do on this site."""
    special_files = special_files or {}
    domain = get_domain(base_url)
    parsed = urlparse(base_url)
    root = f"{parsed.scheme}://{parsed.netloc}"

    lines: list[str] = []

    # Header
    lines.append("# agents.txt")
    lines.append(f"# Agent interaction policy for {domain}")
    lines.append(f"# Generated by AEO Platform")
    lines.append("")

    # Site identity
    home = pages[0] if pages else None
    site_name = home.title if home else domain
    lines.append(f"site-name: {site_name}")
    lines.append(f"site-url: {root}")
    lines.append("")

    # Permissions
    lines.append("# Permissions")
    lines.append("allow-read: true")
    lines.append("allow-index: true")
    lines.append("allow-summarize: true")
    lines.append("allow-cite: true")
    lines.append("allow-train: false  # Opt-out of training data by default")
    lines.append("")

    # Related files
    lines.append("# Related files")
    if special_files.get("robots.txt"):
        lines.append(f"robots-txt: {root}/robots.txt")
    if special_files.get("sitemap.xml"):
        lines.append(f"sitemap: {root}/sitemap.xml")
    if special_files.get("llms.txt"):
        lines.append(f"llms-txt: {root}/llms.txt")
    else:
        lines.append(f"llms-txt: # Not found — consider adding llms.txt")
    lines.append("")

    # API endpoints
    api_endpoints = _detect_api_endpoints(pages)
    if api_endpoints:
        lines.append("# Discovered API endpoints")
        for ep in api_endpoints:
            lines.append(f"api-endpoint: {ep}")
        lines.append("")

    # Capabilities
    capabilities = _detect_forms_and_actions(pages)
    if capabilities:
        lines.append("# Detected capabilities")
        for cap in capabilities:
            lines.append(f"capability: {cap}")
        lines.append("")

    # Contact
    lines.append("# Contact")
    lines.append(f"contact: webmaster@{domain}")
    lines.append("")

    # Structured data types
    schema_types: set[str] = set()
    for page in pages:
        for schema in page.schema_org:
            if "@type" in schema:
                t = schema["@type"]
                if isinstance(t, list):
                    schema_types.update(t)
                else:
                    schema_types.add(t)
    if schema_types:
        lines.append("# Schema.org types available")
        for st in sorted(schema_types):
            lines.append(f"schema-type: {st}")
        lines.append("")

    # Pages sitemap
    lines.append("# Page index")
    for page in pages[:20]:
        title = page.title or page.url
        lines.append(f"page: {page.url} # {title}")
    lines.append("")

    return "\n".join(lines)
