"""Generate llms.txt file content from analysis results."""

from __future__ import annotations

from app.models.schemas import PageAnalysis
from app.utils.helpers import get_domain, truncate


def generate_llms_txt(pages: list[PageAnalysis], base_url: str) -> str:
    """Generate llms.txt following the proposed spec.

    Format:
    # {Site Title}
    > {Site Description}

    ## Pages
    - [{Page Title}]({URL}): {Description}

    ## Key Topics
    - {topic}
    """
    if not pages:
        return ""

    home = pages[0]
    domain = get_domain(base_url)

    lines: list[str] = []

    # Header
    site_title = home.title or domain
    lines.append(f"# {site_title}")
    lines.append("")

    # Site description
    site_desc = home.description or f"Website at {domain}"
    lines.append(f"> {truncate(site_desc, 300)}")
    lines.append("")

    # Pages section
    lines.append("## Pages")
    lines.append("")
    for page in pages:
        title = page.title or page.url
        desc = truncate(page.description, 150) if page.description else ""
        if desc:
            lines.append(f"- [{title}]({page.url}): {desc}")
        else:
            lines.append(f"- [{title}]({page.url})")
    lines.append("")

    # Key topics from headings
    topics: set[str] = set()
    for page in pages:
        for h in page.headings:
            if h["level"] in ("h1", "h2"):
                topics.add(h["text"])
    if topics:
        lines.append("## Key Topics")
        lines.append("")
        for topic in sorted(topics)[:20]:
            lines.append(f"- {topic}")
        lines.append("")

    # Structured data summary
    schema_types: set[str] = set()
    for page in pages:
        for schema in page.schema_org:
            if "@type" in schema:
                t = schema["@type"]
                if isinstance(t, list):
                    schema_types.update(t)
                else:
                    schema_types.add(t)
    if schema_types:
        lines.append("## Structured Data Types")
        lines.append("")
        for st in sorted(schema_types):
            lines.append(f"- {st}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"Generated by AEO Platform for {domain}")
    lines.append("")

    return "\n".join(lines)
